version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306
    env_file:
      - .env
    networks:
      - mynetwork
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    ports:
      - 9000
    volumes:
      - website:/var/www/html/mywebsite/
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure


  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - website:/var/www/html/mywebsite/
    networks:
      - mynetwork
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress


networks:
  mynetwork:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adihaj/data/mariadb/
  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adihaj/data/wordpress/
